project:
  type: book
  output-dir: docs

book:
  title: "Temas selectos de Química Cuántica"
  author: "Montserrat Navarro Espino"
  date: "07/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - math-tools.qmd
    - ej-sencillos.qmd
    - ej-estelect.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



