project:
  type: book
  output-dir: docs

book:
  title: "Temas selectos de Química Cuántica"
  author: "Montserrat Navarro Espino"
  date: "07/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - H-F.qmd
    - DFT.qmd
    - references.qmd

notebook-view:
  - notebook: QuantChem_DFT-AnCarg.ipynb
    title: "Análisis de carga"
    url: https://colab.research.google.com/drive/1-z-jSt-XKtAPTwUHWgcmdKWHyCoMr_lF?usp=sharing

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



