# Teoría de los funcionales de la densidad (DFT)

La Teoría de los Funcionales de la Densidad (DFT, por sus siglas en inglés) trabaja sobre la premisa de que cualquier propiedad de un sistema de varias partículas que interactúan puede visualizarse como un funcional de la densidad del estado basal $n_0(\textbf{r})$ [ver @Martin2008-gc]. A continuación, se presentan tres ejemplos del cálculo de propiedades de diferentes sistemas utilizando GPAW, una librería de Python basada en DFT, el método PAW y el ambiente de simulación atómica ASE [ver @GPAW_2023]. 

## Análisis de cargas

Las cargas de Hirshfeld se definen respecto a a una deformación de la densidad electrónica. Bajo este esquema, para una descripción cuantitativa 
de la distribución de carga en moléculas o sólidos es conveniente dividir el sistema en fragmentos conformados por átomos, lo
que resulta en un compartimento de la densidad y una fuerte localización de la carga entre ellos. Considerando las deformación de la densidad atómica (ssiendo esta una comparación entre átomos enlazados vs átomos libres) 
se definen cargas atómicas netas y momentos multipolo, siendo estos los elementos usados para definir la reorganización de la carga en toda la molécula. Esto permite calcular el potencial electroestático externo y la energía de interacción 
entre moléculas o partes de la misma molécula [ver @Hirshfeld1977].

A continuación, se muestra un ejemplo de código para el análisis de carga para la molécula de HCN en el esquema de Hirshfeld utilizando la librería GPAW.


{{< embed QuantChem_DFT_AnCarg.ipynb#fig-conv-hs >}}


## Orbitales moleculares

Los orbitales moleculares son el producto de una combinación lineal de los orbitales atómicos de los
átomos en una  molécula, lo que representa la distribución electrónica entre dos o más átomos. Estos se obtienen mediante la adición o substracción de las funciones de onda que forman la molécula. En este enfoque, se visualiza a los electrones llenando los orbitale smoleculares uno por uno como sucede en los orbitales atómicos. Esa teoría explica la formación de enlaces a través de la ocupación de orbitales elecgrónicos caraterístico de la molécula [ver @MOELLER1980635]. 


## Estructura de bandas

La estructura de bandas representa los niveles de energía de un sólido, y usualmente de utiliza para determinar si un material es conductor, semiconductor o aislante [ver @FATIMA20233]. Esta estructura de bandas puede ser calculada utilizando diferentes aproximaciones, con sus respectivos beneficios y desventajas, como lo es el método de DFT. 


